apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
  - ../../../base/postgres
  - ../../../base/mysql
  - ../../../base/trino
  - ../../../base/minio
  - ../../../base/prometheus
